# Site
repository: sproogen/resume-theme
favicon: images/favicon1.ico

# Content configuration version
version: 2

# Personal info
name: Bartosz Stanek
title: Renewable Energy Engineer
email: b.stanek95@gmail.com
website: https://bartoszstanek.github.io/

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: bartoszstanek
#github_username:  bartoszstanek
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: bartoszstanek
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# Additional icon links
additional_links:
- title: researchgate.net
  icon: fab fa-researchgate
  url: https://www.researchgate.net/profile/Bartosz-Stanek
- title: CV
  icon: fa fa-file-text-o
  url: https://drive.google.com/file/d/1hmtRlQrwEgOEipheNJ4DvDHkpZLXLj8V/view?usp=sharing

orcid_username: 0000-0002-4136-4092

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/bartoszstanek.jpg
about_content: | # this will include new lines to allow paragraphs
  
  
  Hi, I’m Bartosz, a <mark>renewable engineer</mark>, and a huge enthusiast of <mark>renewable energy sources</mark>, energy storage and new technologies.
  
  My fascination with <mark>RES</mark> technology started almost nine years ago when I decided to study <mark>power and environmental engineering</mark> I graduated from the <mark>Silesian University of Technology</mark> with a BSc Eng. and after an MSc Eng. where I focused on the study of <mark>solar technologies</mark>. Currently, I have been working as a <mark>Renewable Energy Researcher</mark> for almost 5 years, where as part of my <mark>PhD</mark> I am investigating parabolic trough collectors, PV panels, energy storage systems and other technologies related to clean energy generation.
  
  During this period I have acquired extensive technical <mark>theoretical</mark> and <mark>practical</mark> knowledge of energy devices and systems. I have <mark>comprehensively designed and built a solar radiation simulator</mark> and participated in the development of many other research test stations.
  
  Additionally, to researching individual technologies, I developed analyses of entire <mark>energy systems</mark> and their integration. I have performed <mark>long-term analyses</mark> for installations based on energy potential data a feasibility studies.
  
  I have experience collaborating with the industry supported by several collaborative projects and scientific articles. A significant opportunity for development has been the international collaboration with <mark>KTH Royal Institute of Technology</mark>, where I held the position of visiting researcher.  
  
  Check out my [Linkedin](https://www.linkedin.com/in/bartoszstanek/) profile or download my [CV](https://drive.google.com/file/d/1hmtRlQrwEgOEipheNJ4DvDHkpZLXLj8V/view?usp=sharing) for details.
  
  Currently based in Katowice, Poland. Open for Relocation.


  

content:
 # - title: Projects # Title for the section
 #  layout: list # Type of content section (list/text)
 #   content:
  #    - layout: top-middle
  #      title: Super awesome project
  #      link: github.com/sproogen
  #       link_text: Project Website
  #      additional_links:
   #       - title:  sproogen/modern-resume-theme
  #          icon: fab fa-github
  #          url: github.com/sproogen/modern-resume-theme
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #      quote: >
  #        This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #      description: | # this will include new lines to allow paragraphs
  #        I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  #- title: Experience # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: left
  #      title: The Boring Company
  #      link: boringcompany.com
  #      # link_text: boringcompany.com
  #      sub_title: Senior Network System Administrator
  #      caption: November 2017 - Present
  #      quote: >
  #        Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #     description: | # this will include new lines to allow paragraphs
  #          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.



  #- title: Education # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: left
  #      title: Silesian University of Technology
  #      caption: 2019 - now
  #      sub_title: PhD Candidate
  #      #quote: >
  #      description: | # this will include new lines to allow paragraphs
  #        During
        
  #    - layout: left
  #      title: Silesian University of Technology
  #      caption: 2018 - 2019
  #      sub_title: BSc Power Engineering
  #      #quote: >
  #      description: | # this will include new lines to allow paragraphs
  #        During
          
  #    - layout: left
  #      title: Silesian University of Technology
  #      caption: 2014 - 2018
  #      sub_title: BSc Power Engineering
  #      #quote: >
  #      description: | # this will include new lines to allow paragraphs
  #        During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

         
  - title: My goals
    layout: text
    content: | # this will include new lines to allow paragraphs
      
      - increase the share of energy from renewable sources
      - active working on RES to save out environment
      - cooperate with specialists to develop skills and gain knowledge


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
